### ISSUE TITLE
Facilitate providing own ingressController definition

### ISSUE THREAD

**Issue by wizonesolutions** [ten7/ansible-role-flightdeck-cluster#1]
The solution in https://github.com/digitalocean/digitalocean-cloud-controller-manager/blob/master/docs/controllers/services/examples/README.md#accessing-pods-over-a-managed-load-balancer-from-inside-the-cluster requires adding an annotation to the `LoadBalancer` definition. This can't currently be configured in Flight Deck Cluster and requires manually altering or forking the role.

I think any solution would be OK: allowing replacing `ingressController.yml` with a different file or with providing more configuration options for extra labels and annotations.

**Comment by wizonesolutions** [comment]
I realized I forgot to actually share what I did here.

In `tasks/ingressController.yml`, I added this:

```
      {% if flightdeck_cluster.ingressController.hostname %}
        annotations:
          service.beta.kubernetes.io/do-loadbalancer-hostname: "{{ flightdeck_cluster.ingressController.hostname }}"
      {% endif %}
```

under `labels:` in the `Service` definition.

This is not generalized. Since there is no existing `annotations` key, though, perhaps the role could allow the developer to simply define the annotations in a format like:

```
flightdeck_cluster:
  ingressController:
    state: present
    annotations:
      - name: 'service.beta.kubernetes.io/do-loadbalancer-hostname'
        value: 'cluster1.example.com'
```

and then loop over those and template them.
