### ISSUE TITLE
Allow setting storageClass on PVC

### ISSUE THREAD

**Issue by wizonesolutions** [ten7/ansible-role-flightdeck-cluster#2]
I know configuring volumes isn't really documented, but the code is there. Locally I added a `class` parameter to the volume definition. This sets `storageClass` on the PVC. It is so I can use NFS.

I don't have the focus to create a PR right now, but my `tasks/volumes.yml` looks like this:

```
---
- name: Create persistent volume claims
  k8s:
    state: "{{ item.state | default('present') }}"
    definition: |
      ---
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: {{ item.name }}
      spec:
        storageClassName: "{{ item.class | default(omit) }}"
        accessModes:
          - {{ item.mode | default('ReadWriteOnce') }}
        resources:
          requests:
            storage: {{ item.size }}
    kubeconfig: "{{ flightdeck_cluster_kubeconfig | default(omit) }}"
    namespace: "{{ flightdeck_cluster.namespace | default('default') }}"
  loop: "{{ flightdeck_cluster.volumes | default([]) }}"
```
